server:
  port: 8080
spring:
  output.ansi.enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: password
  sql:
    init:
      mode: always